Improve an error message with importing functions
Before:
ERROR: [string "		--Check Error Message Above..."]:57: DGS import data is missing or DGS is not running, please reimport dgs functions(scriptname) 
After:
[DGS] scriptname: DGS import data is missing or DGS is not running, please reimport dgs functions